{
 "title": "WebWatch Analytics",
 "description": "All the possible analytics with the data collected",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "page views",
   "type": "timeseries",
   "description": "This is an aggregated page view panel",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"analytics\")\n  |> range(start: -7d)  // Adjust the time range as needed\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pageviews\")  // Replace \"pageviews\" with the relevant measurement name\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"data_type\"] == \"aggregated\")  // Filter for aggregated data\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)  // Further aggregate if needed, or use 'mean'/'max'/'min'\n  |> yield(name: \"aggregated_pageviews\")\n"
    }
   ]
  },
  {
   "title": "Click: Element_Bar",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"analytics\")\n  |> range(start: -5d)  // Adjust the time range as needed\n  |> filter(fn: (r) => r[\"_measurement\"] == \"clicks\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"data_type\"] == \"aggregated\")  // Filter for aggregated data\n  |> group(columns: [\"target\"])  // Group by the target element\n  |> sum(column: \"_value\")  // Sum the total clicks for each target\n  |> sort(columns: [\"_value\"], desc: true)  // Sort by the number of clicks in descending order\n  |> yield(name: \"click_frequency\")\n"
    }
   ]
  },
  {
   "title": "Image VIews : Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"analytics\")\n  |> range(start: -7d)  // Adjust the time range as needed\n  |> filter(fn: (r) => r[\"_measurement\"] == \"image_views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"view_count\")\n  |> aggregateWindow(every: 1h, fn: sum)  // Aggregate by hour, adjust as needed\n  |> yield(name: \"image_views_over_time\")\n"
    }
   ]
  },
  {
   "title": "Form Submission : stat panel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"analytics\")\n  |> range(start: -7d)  // Adjust the time range as needed\n  |> filter(fn: (r) => r[\"_measurement\"] == \"form_submissions\")\n  |> filter(fn: (r) => r[\"_field\"] == \"submission_count\")\n  |> sum(column: \"_value\")\n  |> yield(name: \"total_form_submissions\")"
    }
   ]
  },
  {
   "title": "Total Downloads : Stat Panel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"analytics\")\n  |> range(start: -7d)  // Adjust the time range as needed\n  |> filter(fn: (r) => r[\"_measurement\"] == \"downloads\")\n  |> filter(fn: (r) => r[\"_field\"] == \"download_count\")\n  |> sum(column: \"_value\")\n  |> yield(name: \"total_downloads\")\n"
    }
   ]
  },
  {
   "title": "Video plays and completions count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"analytics\")\n  |> range(start: -7d)  // Adjust the time range as needed\n  |> filter(fn: (r) => r[\"_measurement\"] == \"video_plays\" or r[\"_measurement\"] == \"video_completions\")\n  |> filter(fn: (r) => r[\"_field\"] == \"play_count\" or r[\"_field\"] == \"completion_count\")\n  |> sum(column: \"_value\")\n  |> yield(name: \"total_video_plays_completions\")\n"
    }
   ]
  },
  {
   "title": "session_duration: bar gauge",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"analytics\")\n  |> range(start: -7d)  // Adjust the time range as needed\n  |> filter(fn: (r) => r[\"_measurement\"] == \"session_durations\")\n  |> filter(fn: (r) => r[\"_field\"] == \"avg_duration\")\n  |> filter(fn: (r) => r[\"data_type\"] == \"aggregated\")\n  |> group(columns: [\"url\"])  // Group by URL\n  |> mean(column: \"_value\")  // Calculate the mean session duration per URL\n  |> sort(columns: [\"_value\"], desc: true)  // Sort by session duration\n  |> yield(name: \"session_duration_comparison\")\n"
    }
   ]
  },
  {
   "title": "Form Submission : time series",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"analytics\")\n  |> range(start: -7d)  // Adjust the time range as needed\n  |> filter(fn: (r) => r[\"_measurement\"] == \"form_submissions\")\n  |> filter(fn: (r) => r[\"_field\"] == \"submission_count\")\n  |> aggregateWindow(every: 1h, fn: sum)  // Aggregate by hour, adjust as needed\n  |> yield(name: \"form_submissions_over_time\")\n"
    }
   ]
  },
  {
   "title": "scroll: time series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"analytics\")\n  |> range(start: -2d)  // Adjust the time range as needed\n  |> filter(fn: (r) => r[\"_measurement\"] == \"scrolls\")\n  |> filter(fn: (r) => r[\"_field\"] == \"scroll_percentage\")\n  |> filter(fn: (r) => r[\"data_type\"] == \"raw\")\n"
    }
   ]
  },
  {
   "title": "scroll: gauge",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"analytics\")\n  |> range(start: -10m)  // Fetch the most recent 10 minutes of data\n  |> filter(fn: (r) => r[\"_measurement\"] == \"scrolls\")\n  |> filter(fn: (r) => r[\"_field\"] == \"scroll_percentage\")\n  |> filter(fn: (r) => r[\"data_type\"] == \"raw\")\n  |> mean(column: \"_value\")  // Calculate the average scroll depth\n  |> yield(name: \"current_average_scroll_depth\")\n"
    }
   ]
  },
  {
   "title": "Click: element_pie_chart",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"analytics\")\n  |> range(start: -7d)  // Adjust the time range as needed\n  |> filter(fn: (r) => r[\"_measurement\"] == \"clicks\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"data_type\"] == \"aggregated\")  // Use \"raw\" if you want raw data instead\n  |> group(columns: [\"target\"])  // Group by the target element (e.g., button, link)\n  |> sum(column: \"_value\")  // Sum the total clicks for each target element\n  |> map(fn: (r) => ({\n      target: r.target,\n      _value: r._value,\n  }))  // Prepare data for pie chart visualization\n  |> yield(name: \"click_distribution\")\n"
    }
   ]
  }
 ]
}